---
# tasks file for periodic_snapshot_sync
- name: "Loop through each VolumeSnapshot and sync its Content"
  include_tasks: sync_one_snapshot.yml
  loop: "{{ all_snapshots_to_sync }}"
  loop_control:
    label: "{{ item.metadata.namespace }}/{{ item.metadata.name }}"
  when: item.status is defined and item.status.boundVolumeSnapshotContentName is defined and item.status.readyToUse | default(false)
