---
- name: "Set snapshot and content objects for the current item"
  set_fact:
    snapshot_object: "{{ item }}"
    content_object: "{{ all_vscs_to_sync | selectattr('metadata.name', 'equalto', item.status.boundVolumeSnapshotContentName) | first }}"

- name: "Debug: Syncing VolumeSnapshot Metadata"
  debug:
    msg: "Processing {{ snapshot_object.kind }} named {{ snapshot_object.metadata.name }}"

- name: "Clean Snapshot resource metadata for DR site"
  set_fact:
    dr_snapshot_object: "{{ snapshot_object | combine({'metadata': snapshot_object.metadata | combine(dr_metadata_overrides)}, recursive=True) }}"
  vars:
    dr_metadata_overrides:
      resourceVersion: null
      uid: null
      creationTimestamp: null
      annotations: "{{ snapshot_object.metadata.annotations | omit('kubectl.kubernetes.io/last-applied-configuration') }}"

- name: "Clean Snapshot resource status for DR site"
  set_fact:
    dr_snapshot_object: "{{ dr_snapshot_object | combine({'status': null}, recursive=True) }}"
  when: dr_snapshot_object.status is defined

- name: "Apply the cleaned Snapshot to the DR cluster"
  kubernetes.core.k8s:
    state: present
    definition: "{{ dr_snapshot_object }}"
    kubeconfig: "{{ dr_kubeconfig_path }}"
  delegate_to: localhost

- name: "Clean VSC resource metadata for DR site"
  set_fact:
    dr_content_object: "{{ content_object | combine({'metadata': content_object.metadata | combine(dr_metadata_overrides)}, recursive=True) }}"
  vars:
    dr_metadata_overrides:
      resourceVersion: null
      uid: null
      creationTimestamp: null
      annotations: "{{ content_object.metadata.annotations | omit('kubectl.kubernetes.io/last-applied-configuration') }}"

- name: "Clean VSC resource status for DR site"
  set_fact:
    dr_content_object: "{{ dr_content_object | combine({'status': null}, recursive=True) }}"
  when: dr_content_object.status is defined

- name: "Apply the cleaned VSC to the DR cluster"
  kubernetes.core.k8s:
    state: present
    definition: "{{ dr_content_object }}"
    kubeconfig: "{{ dr_kubeconfig_path }}"
  delegate_to: localhost
