---
- name: Execute Full DR Failover Workflow
  hosts: localhost
  gather_facts: false
  connection: local

  vars_prompt:
    - name: backup_name
      prompt: "Enter the OADP backup name to restore (leave empty to use the latest)"
      private: no
      default: ""

  vars:
    # This allows the backup_name to be passed in via survey or extra_vars
    oadp_backup_name: "{{ backup_name }}"

  tasks:
    # ----------------------------------------------------------------
    # Block 0: Pre-Failover Actions on Primary Site
    # ----------------------------------------------------------------
    - name: "Pre-Failover: Shut down VMs and set storage read-only"
      block:
        - name: "Shut down VMs on Primary OCP"
          debug:
            msg: "Shutting down VMs on Primary OCP... (Implementation needed)"

        - name: "Set Primary Storage to Read-Only"
          debug:
            msg: "Setting Primary NFS to Read-Only... (Implementation needed)"
      when: execute_pre_failover_steps | default(false) | bool

    # ----------------------------------------------------------------
    # Block 1: Parse OADP Backup
    # ----------------------------------------------------------------
    - name: "Parse OADP Backup to get PV and PVC definitions"
      include_role:
        name: oadp_backup_parser
      vars:
        backup_name: "{{ oadp_backup_name }}"
      register: backup_data

    # ----------------------------------------------------------------
    # Block 2: Final Data Sync
    # ----------------------------------------------------------------
    - name: "Final Data Sync for NFS PVs"
      ansible.posix.synchronize:
        src: "{{ item.spec.nfs.path }}/"
        dest: "rsync://{{ dr_nfs_server_user }}@{{ dr_nfs_server_ip }}:{{ item.spec.nfs.path }}"
        archive: yes
        delete: yes
        # Use --dry-run for verification before actual sync
        # rsync_opts:
        #   - "--dry-run"
      delegate_to: "{{ primary_nfs_server_ip }}"
      loop: "{{ backup_data.pv_info_list }}"
      when:
        - backup_data.pv_info_list is defined
        - item.spec.nfs is defined

    # ----------------------------------------------------------------
    # Block 3: Provision Storage on DR Site
    # ----------------------------------------------------------------
    - name: "Provision Storage on DR Cluster"
      include_role:
        name: dr_storage_provisioner
      vars:
        pv_info_list: "{{ backup_data.pv_info_list }}"
        pvc_info_list: "{{ backup_data.pvc_info_list }}"
      when: backup_data.pv_info_list is defined and backup_data.pvc_info_list is defined

    # ----------------------------------------------------------------
    # Block 4: Trigger OADP Restore on DR Site
    # ----------------------------------------------------------------
    - name: "Trigger OADP Restore on DR Cluster"
      include_role:
        name: oadp_restore_trigger
      vars:
        # Use the backup name found by the parser role
        oadp_backup_name: "{{ backup_data.backup_name }}"

    # ----------------------------------------------------------------
    # Block 5: Post-Failover Verification and Cleanup
    # ----------------------------------------------------------------
    - name: "Post-Failover Actions"
      block:
        - name: "Verify VM Status on DR Cluster"
          debug:
            msg: "Verifying that VMs are running on the DR cluster... (Implementation needed)"

        - name: "Clean up temporary files"
          ansible.builtin.file:
            path: "{{ backup_data.temp_backup_dir }}"
            state: absent
          when: backup_data.temp_backup_dir is defined

        - name: "Generate Failover Report"
          debug:
            msg: "Failover process completed for backup {{ backup_data.backup_name }}."
