---
- name: Listen for OCP Persistent Volume Changes (Debug)
  hosts: localhost

  # This pre_tasks block will run before any event sources start
  pre_tasks:
    - name: Print debug information before starting source
      ansible.builtin.debug:
        msg:
          - "Attempting to connect to host: {{ lookup('env', 'K8S_HOST') }}"
          - "API Key starts with: {{ (lookup('env', 'K8S_API_KEY', default=''))[:10] }}..."
          - "API Key length: {{ (lookup('env', 'K8S_API_KEY', default='')) | length }}"
          - "HTTPS_PROXY is: {{ lookup('env', 'HTTPS_PROXY', default='Not Set') }}"
          - "NO_PROXY is: {{ lookup('env', 'NO_PROXY', default='Not Set') }}"

  sources:
      - sabre1041.eda.k8s:
          api_key: "{{ k8s_api_key }}" # Added for API authentication
          host: "{{ k8s_host }}" # Added for API host
          validate_certs: false
          api_version: v1
          kind: PersistentVolume
          namespace: "" # Listen in all namespaces
  rules:
      # Rule: Handle creation and modification of NFS PVs
      - name: Handle NFS PV Create or Update (Debug)
        condition: >
          (event.type == "ADDED" or event.type == "MODIFIED") and
          event.resource.spec.storageClassName == "nfs-dynamic"
        action:
          debug:
            msg: "NFS PV Created or Modified: {{ event.resource.metadata.name }} (Type: {{ event.type }})"

      # Rule: Handle deletion of NFS PVs
      - name: Handle NFS PV Deletion (Debug)
        condition: >
          event.type == "DELETED" and
          event.resource.spec.storageClassName == "nfs-dynamic"
        action:
          debug:
            msg: "NFS PV Deleted: {{ event.resource.metadata.name }} (Type: {{ event.type }})"
