---
- name: 响应OpenShift存储事件
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000 # 确保这个端口与您在deployment.yaml中配置的URL端口一致

  rules:
    - name: 处理新的或更新的PV
      condition: event.payload.kind == "PersistentVolume" and (event.payload.type == "ADDED" or event.payload.type == "MODIFIED")
      action:
        debug:
          msg: "PV事件触发: {{ event.payload.type }} on PV named '{{ event.payload.resource.metadata.name }}' with StorageClass '{{ event.payload.resource.spec.storageClassName }}'"

    - name: 处理被删除的PV
      condition: event.payload.kind == "PersistentVolume" and event.payload.type == "DELETED"
      action:
        debug:
          msg: "PV删除事件: PV '{{ event.payload.resource.metadata.name }}' was deleted."

    - name: 处理新的Volume Snapshot
      condition: event.payload.kind == "VolumeSnapshot" and event.payload.type == "ADDED"
      action:
        run_playbook: # 示例：触发一个备份剧本
          name: playbooks/handle_new_snapshot.yml
          extra_vars:
            snapshot_name: "{{ event.payload.resource.metadata.name }}"
            source_pvc: "{{ event.payload.resource.spec.source.persistentVolumeClaimName }}"
