---
- name: Listen for OCP Persistent Volume Changes
  hosts: localhost
  sources:
    - ansible.eda.k8s:
        api_version: v1
        kind: PersistentVolume
        namespace: "" # Listen in all namespaces

  rules:
    # Rule: Handle creation and modification of NFS PVs
    - name: Handle NFS PV Create or Update
      condition: >
        (event.type == "ADDED" or event.type == "MODIFIED") and
        event.resource.spec.storageClassName == "nfs-dynamic"
      action:
        run_job_template:
          name: "EDA - Sync NFS PV to DR"
          organization: "Default"
          job_args:
            extra_vars:
              pv_object: "{{ event.resource }}" # Pass the entire PV object as a variable

    # Rule: Handle deletion of NFS PVs
    - name: Handle NFS PV Deletion
      condition: >
        event.type == "DELETED" and
        event.resource.spec.storageClassName == "nfs-dynamic"
      action:
        run_job_template:
          name: "EDA - Delete NFS PV from DR"
          organization: "Default"
          job_args:
            extra_vars:
              pv_object: "{{ event.resource }}"
