# tasks file for periodic_pv_pvc_sync
- name: "Loop through each PVC and sync its PV"
  include_tasks: sync_one_pvc.yml
  loop: "{{ all_pvcs_to_sync }}"
  loop_control:
    label: "{{ item.metadata.namespace }}/{{ item.metadata.name }}"
  when: item.spec.volumeName is defined
